'use strict';

const map = require('lodash/map');
const filter = require('lodash/filter');
const orderBy = require('lodash/orderBy');
const moment = require('moment-timezone');

require('moment-timezone/builds/moment-timezone-with-data-2012-2022.js');

const oldTimeZones = [    
    { key: 'Pacific/Midway'},
    { key: 'America/Monterrey'},
    { key: 'America/Bogota'},
    { key: 'America/Argentina/Buenos_Aires'},
    { key: 'Africa/Monrovia'},
    { key: 'Europe/Amsterdam'},
    { key: 'Europe/Belgrade'},
    { key: 'Europe/Berlin'},
    { key: 'Europe/Bratislava'},
    { key: 'Africa/Lagos'},
    { key: 'Africa/Johannesburg'},
    { key: 'Asia/Muscat'},
    { key: 'Asia/Karachi'},
    { key: 'Asia/Tashkent'},
    { key: 'Asia/Yekaterinburg'},
    { key: 'Asia/Bangkok'},
    { key: 'Asia/Krasnoyarsk'},
    { key: 'Pacific/Kwajalein'},
    { key: 'Pacific/Fiji'},
    { key: 'Pacific/Tongatapu'},

    // Fix for timezones
    { key: 'Etc/Greenwich', value: 'Etc/GMT'},
    { key: 'US/Central', value: 'America/Chicago'},
    { key: 'US/Mountain', value: 'America/Denver'},
    { key: 'US/Eastern', value: 'America/New_York'},
    { key: 'America/Godthab', value: 'America/Nuuk' },
    { key: 'Canada/Atlantic', value: 'America/Halifax'},
    { key: 'Asia/Ulan_Bator', value: 'Asia/Ulaanbaatar'},
    { key: 'America/Nipigon', value: 'America/Toronto'},
    { key: 'Canada/Newfoundland', value: 'America/St_Johns'},
    { key: 'America/Thunder_Bay', value: 'America/Toronto'}, 
    { key: 'America/Pangnirtung', value: 'America/Iqaluit'}, 
    { key: 'America/Rainy_River', value: 'America/Winnipeg'}, 
    { key: 'America/Yellowknife', value: 'America/Edmonton'}, 
    { key: 'US/East-Indiana', value: 'America/Indiana/Indianapolis'},

    { key: 'UTC', value: 'UTC'},
    { key: 'EET', value: 'Europe/Kyiv'},
    { key: 'Hongkong', value: 'Asia/Hong_Kong'},
    { key: 'Europe/Kiev', value: 'Europe/Kyiv'},
    { key: 'America/La_Paz', value: 'America/La_Paz'},
    { key: 'Europe/London', value: 'Europe/London'},
    { key: 'Asia/Calcutta', value: 'Asia/Kolkata'},
    { key: 'Pacific/Honolulu', value: 'Pacific/Honolulu'},
    { key: 'Europe/Nicosia', value: 'Europe/Kyiv'},
    { key: 'Europe/Moscow', value: 'Europe/Moscow'},
    { key: 'Europe/Uzhgorod', value: 'Europe/Kyiv'},
    { key: 'Pacific/Auckland', value: 'Pacific/Auckland'},
    { key: 'America/Noronha', value: 'America/Noronha'},
    { key: 'America/Sao_Paulo', value: 'America/Sao_Paulo'},
    { key: 'Europe/Zaporozhye', value: 'Europe/Kyiv'},
    { key: 'America/Managua', value: 'America/Managua'},
    { key: 'Asia/Kuala_Lumpur', value: 'Asia/Kuala_Lumpur'},
    { key: 'America/Mexico_City', value: 'America/Mexico_City'},
    { key: 'Pacific/Port_Moresby', value: 'Pacific/Port_Moresby'},
    { key: 'Atlantic/Cape_Verde', value: 'Atlantic/Cape_Verde'},
    { key: 'America/Los_Angeles', value: 'America/Los_Angeles'},
];

const depericated = [
    { key: 'Africa/Asmera'}, 
    { key: 'Africa/Timbuktu'}, 
    { key: 'America/Argentina/ComodRivadavia'}, 
    { key: 'America/Atka'}, 
    { key: 'America/Nipigon'}, 
    { key: 'America/Pangnirtung'}, 
    { key: 'America/Rainy_River'}, 
    { key: 'America/Buenos_Aires'}, 
    { key: 'America/Catamarca'}, 
    { key: 'America/Coral_Harbour'}, 
    { key: 'America/Thunder_Bay'}, 
    { key: 'America/Yellowknife'}, 
    { key: 'America/Cordoba'}, 
    { key: 'America/Ensenada'}, 
    { key: 'America/Fort_Wayne'}, 
    { key: 'America/Godthab'}, 
    { key: 'America/Indianapolis'}, 
    { key: 'America/Jujuy'}, 
    { key: 'America/Knox_IN'}, 
    { key: 'America/Louisville'}, 
    { key: 'America/Mendoza'}, 
    { key: 'America/Montreal'}, 
    { key: 'America/Porto_Acre'}, 
    { key: 'America/Rosario'}, 
    { key: 'America/Santa_Isabel'}, 
    { key: 'America/Shiprock'}, 
    { key: 'America/Virgin'}, 
    { key: 'Antarctica/South_Pole'}, 
    { key: 'Asia/Ashkhabad'}, 
    { key: 'Asia/Calcutta'}, 
    { key: 'Asia/Chongqing'}, 
    { key: 'Asia/Chungking'}, 
    { key: 'Asia/Dacca'}, 
    { key: 'Asia/Harbin'}, 
    { key: 'Asia/Istanbul'}, 
    { key: 'Asia/Kashgar'}, 
    { key: 'Asia/Katmandu'}, 
    { key: 'Asia/Macao'}, 
    { key: 'Asia/Rangoon'}, 
    { key: 'Asia/Saigon'}, 
    { key: 'Asia/Tel_Aviv'}, 
    { key: 'Asia/Thimbu'}, 
    { key: 'Asia/Ujung_Pandang'}, 
    { key: 'Asia/Ulan_Bator'}, 
    { key: 'Atlantic/Faeroe'}, 
    { key: 'Atlantic/Jan_Mayen'}, 
    { key: 'Australia/ACT'}, 
    { key: 'Australia/Canberra'}, 
    { key: 'Australia/Currie'}, 
    { key: 'Australia/LHI'}, 
    { key: 'Australia/North'}, 
    { key: 'Australia/NSW'}, 
    { key: 'Australia/Queensland'}, 
    { key: 'Australia/South'}, 
    { key: 'Australia/Tasmania'}, 
    { key: 'Australia/Victoria'}, 
    { key: 'Australia/West'}, 
    { key: 'Australia/Yancowinna'}, 
    { key: 'Brazil/Acre'}, 
    { key: 'Brazil/DeNoronha'}, 
    { key: 'Brazil/East'}, 
    { key: 'Brazil/West'}, 
    { key: 'Canada/Atlantic'}, 
    { key: 'Canada/Central'}, 
    { key: 'Canada/Eastern'}, 
    { key: 'Canada/Mountain'}, 
    { key: 'Canada/Newfoundland'}, 
    { key: 'Canada/Pacific'}, 
    { key: 'Canada/Saskatchewan'}, 
    { key: 'Canada/Yukon'}, 
    { key: 'CET'}, 
    { key: 'Chile/Continental'}, 
    { key: 'Chile/EasterIsland'}, 
    { key: 'CST6CDT'}, 
    { key: 'Cuba'}, 
    { key: 'EET'}, 
    { key: 'Egypt'}, 
    { key: 'Eire'}, 
    { key: 'EST'}, 
    { key: 'EST5EDT'}, 
    { key: 'Etc/GMT'}, 
    { key: 'Etc/GMT+0'}, 
    { key: 'Etc/GMT+1'}, 
    { key: 'Etc/GMT+10'}, 
    { key: 'Etc/GMT+11'}, 
    { key: 'Etc/GMT+12'}, 
    { key: 'Etc/GMT+2'}, 
    { key: 'Etc/GMT+3'}, 
    { key: 'Etc/GMT+4'}, 
    { key: 'Etc/GMT+5'}, 
    { key: 'Etc/GMT+6'}, 
    { key: 'Etc/GMT+7'}, 
    { key: 'Etc/GMT+8'}, 
    { key: 'Etc/GMT+9'}, 
    { key: 'Etc/GMT-0'}, 
    { key: 'Etc/GMT-1'}, 
    { key: 'Etc/GMT-10'}, 
    { key: 'Etc/GMT-11'}, 
    { key: 'Etc/GMT-12'}, 
    { key: 'Etc/GMT-13'}, 
    { key: 'Etc/GMT-14'}, 
    { key: 'Etc/GMT-2'}, 
    { key: 'Etc/GMT-3'}, 
    { key: 'Etc/GMT-4'}, 
    { key: 'Etc/GMT-5'}, 
    { key: 'Etc/GMT-6'}, 
    { key: 'Etc/GMT-7'}, 
    { key: 'Etc/GMT-8'}, 
    { key: 'Etc/GMT-9'}, 
    { key: 'Etc/GMT0'}, 
    { key: 'Etc/Greenwich'}, 
    { key: 'Etc/UCT'}, 
    { key: 'Etc/Universal'}, 
    { key: 'Etc/UTC'}, 
    { key: 'Etc/Zulu'}, 
    { key: 'Europe/Belfast'}, 
    { key: 'Europe/Nicosia'}, 
    { key: 'Europe/Tiraspol'}, 
    { key: 'Factory'}, 
    { key: 'GB'}, 
    { key: 'GB-Eire'}, 
    { key: 'GMT'}, 
    { key: 'GMT+0'}, 
    { key: 'GMT-0'}, 
    { key: 'GMT0'}, 
    { key: 'Greenwich'}, 
    { key: 'Hongkong'}, 
    { key: 'HST'}, 
    { key: 'Iceland'}, 
    { key: 'Iran'}, 
    { key: 'Israel'}, 
    { key: 'Jamaica'}, 
    { key: 'Japan'}, 
    { key: 'Kwajalein'}, 
    { key: 'Libya'}, 
    { key: 'MET'}, 
    { key: 'Mexico/BajaNorte'}, 
    { key: 'Mexico/BajaSur'}, 
    { key: 'Mexico/General'}, 
    { key: 'MST'}, 
    { key: 'MST7MDT'}, 
    { key: 'Navajo'}, 
    { key: 'NZ'}, 
    { key: 'NZ-CHAT'}, 
    { key: 'Pacific/Enderbury'}, 
    { key: 'Pacific/Johnston'}, 
    { key: 'Pacific/Ponape'}, 
    { key: 'Pacific/Samoa'}, 
    { key: 'Pacific/Truk'}, 
    { key: 'Pacific/Yap'}, 
    { key: 'Poland'}, 
    { key: 'Portugal'}, 
    { key: 'PRC'}, 
    { key: 'PST8PDT'}, 
    { key: 'ROC'}, 
    { key: 'ROK'}, 
    { key: 'Singapore'}, 
    { key: 'Turkey'}, 
    { key: 'UCT'}, 
    { key: 'Universal'}, 
    { key: 'US/Alaska'}, 
    { key: 'US/Aleutian'}, 
    { key: 'US/Arizona'}, 
    { key: 'US/Central'}, 
    { key: 'US/East-Indiana'}, 
    { key: 'US/Eastern'}, 
    { key: 'US/Hawaii'}, 
    { key: 'US/Indiana-Starke'}, 
    { key: 'US/Michigan'}, 
    { key: 'US/Mountain'}, 
    { key: 'US/Pacific'}, 
    { key: 'US/Samoa'}, 
    { key: 'UTC'}, 
    { key: 'W-SU'}, 
    { key: 'WET'}, 
    { key: 'Zulu'}
];

const tzNames = moment.tz.names();
const getFriendlyName = function(tzName) {

    const tzObj = moment().tz(tzName);
    const prefix = '(' + tzObj.format('Z') + ') ';
   
    const found = filter(oldTimeZones, { key: tzName });
    if (found !== undefined && found[0]) {
        return {
            key: tzName,
            depericated: false,
            name: prefix + found[0].key,
            value: (found[0].value !== undefined) ? found[0].value : tzName,
        }    
    }

    const foundDepericated = filter(depericated, { key: tzName });
    if (foundDepericated.length > 0 && foundDepericated[0] && foundDepericated[0].key) {
        return {
            key: tzName,
            value: tzName,
            depericated: true,
            name: prefix + tzName,
        }
    }

    return {
        key: tzName,
        value: tzName,
        depericated: false,
        name: prefix + tzName
    }
}

const newList = map(tzNames, (tzName) => getFriendlyName(tzName))
                .filter((record) => !record.depericated);

const timezones = orderBy(newList, ['key'], ['asc']);

const guess = () => moment.tz.guess() || 'UTC';
const getZone = (newTz) => moment.tz.zone(newTz);
const knownTimezone = (customerTimezone) => filter(timezones, { key: customerTimezone }).length > 0;
const getTimeZoneName = (customerTimezone) => '(' + moment().tz(customerTimezone).format('Z') + ') ' + customerTimezone;

module.exports = {
    guess,
    getZone,
    knownTimezone,
    getTimeZoneName,
    list: timezones
};
